logging:
  mode: offline
  project: CellVTA_MoNuSeg_unified_aug
  notes: CellVTA_MoNuSeg_unified_aug
  log_comment: CellVTA_MoNuSeg_unified_aug
  tags:
    - unified-augmentation
    - monuseg
    - cellvta
  wandb_dir: "logs"
  log_dir: "logs"
  level: "info"
  log_images:
  group:

random_seed: 19

gpu: 0

data:
  dataset: MoNuSeg
  dataset_path: "datasets/monuseg_cellvta_1024"
  train_folds: [0]
  val_folds: [1]
  test_folds: [2]
  num_nuclei_classes: 2
  num_tissue_classes: 1
  input_shape: 256
  train_repeat: 16

model:
  backbone: UNI_Adapter
  pretrained_encoder: "pretrained_models/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin"
  pretrained:
  embed_dim: 1024
  input_channels:
  depth: 24
  num_heads: 16
  extract_layers:
  shared_decoders:
  regression_loss:

loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
  hv_map:
    mse:
      loss_fn: mse_loss_maps
      weight: 2.5
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 2
  tissue_types:
    ce:
      loss_fn: CrossEntropyLoss
      weight: 0.1

training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 8
  epochs: 50
  optimizer: AdamW
  early_stopping_patience: 50
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 51
  eval_every: 5

transformations:
  randomscale:
    p: 1.0
    scale_limit: 0.2
  padifneeded:
    p: 1.0
  randomcrop:
    p: 1.0
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  pixelaug_oneof:
    p: 1.0
    gaussian_blur_limit: [1, 5]
    median_blur_limit: 5
    gaussnoise_var_limit: [0.0, 162.5625]
  colorjitter:
    p: 1.0
    brightness: 0.1019608
    contrast: 0.25
    saturation: 0.2
    hue: 0.0313725
  normalize:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

eval_checkpoint: "model_best.pth"
